/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_roseboy_classfinal_jni_NativeDecryptor */

#ifndef _Included_net_roseboy_classfinal_jni_NativeDecryptor
#define _Included_net_roseboy_classfinal_jni_NativeDecryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_roseboy_classfinal_jni_NativeDecryptor
 * Method:    nativeDecryptClass
 * Signature: ([BLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_roseboy_classfinal_jni_NativeDecryptor_nativeDecryptClass
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     net_roseboy_classfinal_jni_NativeDecryptor
 * Method:    nativeSetCrc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_roseboy_classfinal_jni_NativeDecryptor_nativeSetCrc
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_roseboy_classfinal_jni_NativeDecryptor
 * Method:    nativeVerifyIntegrity
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_net_roseboy_classfinal_jni_NativeDecryptor_nativeVerifyIntegrity
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
