/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class i_i_i_NativeDecryptor */

#ifndef _Included_i_i_i_NativeDecryptor
#define _Included_i_i_i_NativeDecryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     i_i_i_NativeDecryptor
 * Method:    nativeGetPwd
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_i_i_i_NativeDecryptor_nativeGetPwd
  (JNIEnv *, jclass);

/*
 * Class:     i_i_i_NativeDecryptor
 * Method:    nativeDeriveKey
 * Signature: ()[C
 */
JNIEXPORT jcharArray JNICALL Java_i_i_i_NativeDecryptor_nativeDeriveKey
  (JNIEnv *, jclass);

/*
 * Class:     i_i_i_NativeDecryptor
 * Method:    nativeDecrypt
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_i_i_i_NativeDecryptor_nativeDecrypt
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     i_i_i_NativeDecryptor
 * Method:    nativeMd5
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_i_i_i_NativeDecryptor_nativeMd5
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     i_i_i_NativeDecryptor
 * Method:    nativeFullDecrypt
 * Signature: ([BLjava/lang/String;[C)[B
 */
JNIEXPORT jbyteArray JNICALL Java_i_i_i_NativeDecryptor_nativeFullDecrypt
  (JNIEnv *, jclass, jbyteArray, jstring, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
